const Country = require('../models/country.model');
const keys = require('../config/keys');


const mongoose = require('mongoose');

const uri = keys.mongo.dbURI;

mongoose.connect(uri, {useNewUrlParser: true, useUnifiedTopology: true})
        .then( () => {console.log('Connection to Mongo is successful');})
        .catch( err => {console.log('Connection error', err);})

const countryData = [ new Country({_id: 1, name: 'Afghanistan'}),
new Country({_id: 2, name:'Albania'}),
new Country({_id: 3, name:'Algeria'}),
new Country({_id: 4, name:'Andorra'}),
new Country({_id: 5, name:'Angola'}),
new Country({_id: 6, name:'Antigua and Barbuda'}),
new Country({_id: 7, name:'Argentina'}),
new Country({_id: 8, name:'Armenia'}),
new Country({_id: 9, name:'Australia'}),
new Country({_id: 10, name:'Austria'}),
new Country({_id: 11, name:'Azerbaijan'}),
new Country({_id: 12, name:'Bahamas'}),
new Country({_id: 13, name:'Bahrain'}),
new Country({_id: 14, name:'Bangladesh'}),
new Country({_id: 15, name:'Barbados'}),
new Country({_id: 16, name:'Belarus'}),
new Country({_id: 17, name:'Belgium'}),
new Country({_id: 18, name:'Belize'}),
new Country({_id: 19, name:'Benin'}),
new Country({_id: 20, name:'Bhutan'}),
new Country({_id: 21, name:'Bolivia'}),
new Country({_id: 22, name:'Bosnia and Herzegovina'}),
new Country({_id: 23, name:'Botswana'}),
new Country({_id: 24, name:'Brazil'}),
new Country({_id: 25, name:'Brunei'}),
new Country({_id: 26, name:'Bulgaria'}),
new Country({_id: 27, name:'Burkina Faso'}),
new Country({_id: 28, name:'Burundi'}),
new Country({_id: 29, name:'Côte d\'Ivoire'}),
new Country({_id: 30, name:'Cabo Verde'}),
new Country({_id: 31, name:'Cambodia'}),
new Country({_id: 32, name:'Cameroon'}),
new Country({_id: 33, name:'Canada'}),
new Country({_id: 34, name:'Central African Republic'}),
new Country({_id: 35, name:'Chad'}),
new Country({_id: 36, name:'Chile'}),
new Country({_id: 37, name:'China'}),
new Country({_id: 38, name:'Colombia'}),
new Country({_id: 39, name:'Comoros'}),
new Country({_id: 40, name:'Congo'}),
new Country({_id: 41, name:'Costa Rica'}),
new Country({_id: 42, name:'Croatia'}),
new Country({_id: 43, name:'Cuba'}),
new Country({_id: 44, name:'Cyprus'}),
new Country({_id: 45, name:'Czechia'}),
new Country({_id: 46, name:'Democratic Republic of the Congo'}),
new Country({_id: 47, name:'Denmark'}),
new Country({_id: 48, name:'Djibouti'}),
new Country({_id: 49, name:'Dominica'}),
new Country({_id: 50, name:'Dominican Republic'}),
new Country({_id: 51, name:'Ecuador'}),
new Country({_id: 52, name:'Egypt'}),
new Country({_id: 53, name:'El Salvador'}),
new Country({_id: 54, name:'Equatorial Guinea'}),
new Country({_id: 55, name:'Eritrea'}),
new Country({_id: 56, name:'Estonia'}),
new Country({_id: 57, name:'Eswatini'}),
new Country({_id: 58, name:'Ethiopia'}),
new Country({_id: 59, name:'Fiji'}),
new Country({_id: 60, name:'Finland'}),
new Country({_id: 61, name:'France'}),
new Country({_id: 62, name:'Gabon'}),
new Country({_id: 63, name:'Gambia'}),
new Country({_id: 64, name:'Georgia'}),
new Country({_id: 65, name:'Germany'}),
new Country({_id: 66, name:'Ghana'}),
new Country({_id: 67, name:'Greece'}),
new Country({_id: 68, name:'Grenada'}),
new Country({_id: 69, name:'Guatemala'}),
new Country({_id: 70, name:'Guinea'}),
new Country({_id: 71, name:'Guinea-Bissau'}),
new Country({_id: 72, name:'Guyana'}),
new Country({_id: 73, name:'Haiti'}),
new Country({_id: 74, name:'Holy See'}),
new Country({_id: 75, name:'Honduras'}),
new Country({_id: 76, name:'Hungary'}),
new Country({_id: 77, name:'Iceland'}),
new Country({_id: 78, name:'India'}),
new Country({_id: 79, name:'Indonesia'}),
new Country({_id: 80, name:'Iran'}),
new Country({_id: 81, name:'Iraq'}),
new Country({_id: 82, name:'Ireland'}),
new Country({_id: 83, name:'Israel'}),
new Country({_id: 84, name:'Italy'}),
new Country({_id: 85, name:'Jamaica'}),
new Country({_id: 86, name:'Japan'}),
new Country({_id: 87, name:'Jordan'}),
new Country({_id: 88, name:'Kazakhstan'}),
new Country({_id: 89, name:'Kenya'}),
new Country({_id: 90, name:'Kiribati'}),
new Country({_id: 91, name:'Kuwait'}),
new Country({_id: 92, name:'Kyrgyzstan'}),
new Country({_id: 93, name:'Laos'}),
new Country({_id: 94, name:'Latvia'}),
new Country({_id: 95, name:'Lebanon'}),
new Country({_id: 96, name:'Lesotho'}),
new Country({_id: 97, name:'Liberia'}),
new Country({_id: 98, name:'Libya'}),
new Country({_id: 99, name:'Liechtenstein'}),
new Country({_id: 100, name:'Lithuania'}),
new Country({_id: 101, name:'Luxembourg'}),
new Country({_id: 102, name:'Madagascar'}),
new Country({_id: 103, name:'Malawi'}),
new Country({_id: 104, name:'Malaysia'}),
new Country({_id: 105, name:'Maldives'}),
new Country({_id: 106, name:'Mali'}),
new Country({_id: 107, name:'Malta'}),
new Country({_id: 108, name:'Marshall Islands'}),
new Country({_id: 109, name:'Mauritania'}),
new Country({_id: 110, name:'Mauritius'}),
new Country({_id: 111, name:'Mexico'}),
new Country({_id: 112, name:'Micronesia'}),
new Country({_id: 113, name:'Moldova'}),
new Country({_id: 114, name:'Monaco'}),
new Country({_id: 115, name:'Mongolia'}),
new Country({_id: 116, name:'Montenegro'}),
new Country({_id: 117, name:'Morocco'}),
new Country({_id: 118, name:'Mozambique'}),
new Country({_id: 119, name:'Myanmar'}),
new Country({_id: 120, name:'Namibia'}),
new Country({_id: 121, name:'Nauru'}),
new Country({_id: 122, name:'Nepal'}),
new Country({_id: 123, name:'Netherlands'}),
new Country({_id: 124, name:'New Zealand'}),
new Country({_id: 125, name:'Nicaragua'}),
new Country({_id: 126, name:'Niger'}),
new Country({_id: 127, name:'Nigeria'}),
new Country({_id: 128, name:'North Korea'}),
new Country({_id: 129, name:'North Macedonia'}),
new Country({_id: 130, name:'Norway'}),
new Country({_id: 131, name:'Oman'}),
new Country({_id: 132, name:'Pakistan'}),
new Country({_id: 133, name:'Palau'}),
new Country({_id: 134, name:'Palestine State'}),
new Country({_id: 135, name:'Panama'}),
new Country({_id: 136, name:'Papua New Guinea'}),
new Country({_id: 137, name:'Paraguay'}),
new Country({_id: 138, name:'Peru'}),
new Country({_id: 139, name:'Philippines'}),
new Country({_id: 140, name:'Poland'}),
new Country({_id: 141, name:'Portugal'}),
new Country({_id: 142, name:'Qatar'}),
new Country({_id: 143, name:'Romania'}),
new Country({_id: 144, name:'Russia'}),
new Country({_id: 145, name:'Rwanda'}),
new Country({_id: 146, name:'Saint'}),
new Country({_id: 147, name:'Saint Lucia'}),
new Country({_id: 148, name:'Saint Vincent and the Grenadines'}),
new Country({_id: 149, name:'Samoa'}),
new Country({_id: 150, name:'San Marino'}),
new Country({_id: 151, name:'Sao Tome and Principe'}),
new Country({_id: 152, name:'Saudi Arabia'}),
new Country({_id: 153, name:'Senegal'}),
new Country({_id: 154, name:'Serbia'}),
new Country({_id: 155, name:'Seychelles'}),
new Country({_id: 156, name:'Sierra Leone'}),
new Country({_id: 157, name:'Singapore'}),
new Country({_id: 158, name:'Slovakia'}),
new Country({_id: 159, name:'Slovenia'}),
new Country({_id: 160, name:'Solomon Islands'}),
new Country({_id: 161, name:'Somalia'}),
new Country({_id: 162, name:'South Africa'}),
new Country({_id: 163, name:'South Korea'}),
new Country({_id: 164, name:'South Sudan'}),
new Country({_id: 165, name:'Spain'}),
new Country({_id: 166, name:'Sri Lanka'}),
new Country({_id: 167, name:'Sudan'}),
new Country({_id: 168, name:'Suriname'}),
new Country({_id: 169, name:'Sweden'}),
new Country({_id: 170, name:'Switzerland'}),
new Country({_id: 171, name:'Syria'}),
new Country({_id: 172, name:'Tajikistan'}),
new Country({_id: 173, name:'Tanzania'}),
new Country({_id: 174, name:'Thailand'}),
new Country({_id: 175, name:'Timor-Leste'}),
new Country({_id: 176, name:'Togo'}),
new Country({_id: 177, name:'Tonga'}),
new Country({_id: 178, name:'Trinidad and Tobago'}),
new Country({_id: 179, name:'Tunisia'}),
new Country({_id: 180, name:'Turkey'}),
new Country({_id: 181, name:'Turkmenistan'}),
new Country({_id: 182, name:'Tuvalu'}),
new Country({_id: 183, name:'Uganda'}),
new Country({_id: 184, name:'Ukraine'}),
new Country({_id: 185, name:'United Arab Emirates'}),
new Country({_id: 186, name:'United Kingdom'}),
new Country({_id: 187, name:'United States of America'}),
new Country({_id: 188, name:'Uruguay'}),
new Country({_id: 189, name:'Uzbekistan'}),
new Country({_id: 190, name:'Vanuatu'}),
new Country({_id: 191, name:'Venezuela'}),
new Country({_id: 192, name:'Vietnam'}),
new Country({_id: 193, name:'Yemen'}),
new Country({_id: 194, name:'Zambia'}),
new Country({_id: 195, name:'Zimbabwe'})];

let count = 0;
countryData.forEach(country => {
    country.save(() => {
        count++;
        console.log('record saved', country._id);
        if(count == countryData.length) {
            closeConnection();
        }
    });
    
});

function closeConnection() {
    mongoose.disconnect();
}